### ISSUE TITLE
description of environment:synchronize is vague

### ISSUE THREAD

**Issue by fuzzbomb** [platformsh/platformsh-cli#421]
`platform help environment:synchronize` tells me:

Description: Synchronize an environment

Which isn't much to go on - it just repeat the words in the command name.

The crucial bits of information this needs are:
- what changes when you run it?
- which direction does it go?

Synchronize "an" environment? Just one, not two environments?

In other words, I have no idea whether this will help me get a copy of the database from production environment onto my development laptop... or is it intended to go the other way around?

Or does it synchronize two environments which are on the platform.sh hosting?

**Comment by pjcdawkins** [comment]
It was concise at least :) but you're right - perhaps "Synchronize an environment's code and/or data from its parent" would be clearer.

It synchronizes from a (platform.sh) parent environment to the (platform.sh) child environment. "Code" means there will be a git merge. "Data" means all files in all services (via an LVM snapshot type thing) (including static files, databases, logs, search indices) will be synced.

**Comment by pjcdawkins** [comment]
Fixed in [v2.13.0](https://github.com/platformsh/platformsh-cli/releases/tag/v2.13.0)

**Comment by fuzzbomb** [comment]
I'm still not clear what this does. The from/to aspect has been clarified, but only partially. Now two new terms have been introduced without explanation.

I haven't dared to run this command. Data will change... _somewhere_.

- What do the terms "parent" and "child" environment refer to?
- Are both of them hosted on platform.sh? (If so, how do we know which is which?)
- Or are they referring to a developer's local environment (e.g. running on a laptop) vs remote environments hosted on platform.sh?
- What happens if a static file is present on the child, but not present in the parent? Will it remain in place, or be removed from the child environment?

**Comment by sruggier** [comment]
This page should indirectly answer most of your questions: https://docs.platform.sh/user_guide/overview/environments.html.

Regarding static files, it would depend on whether they were a part of your Git repository (code), or if they're static files served from a writable directory that you've mounted somewhere under your document root (data). If you sync a change that removes the file, or data from a parent where the file has been deleted from storage, then yes, it would be removed from the child.

**Comment by OriPekelman** [comment]
For posterity I will answer inline some of the questions:
I haven't dared to run this command. Data will change... somewhere.

>What do the terms "parent" and "child" environment refer to?
Platform.sh environments represent git branches. And Platform.sh respects the tree structure of git. So if you branched the "hotfix_3" branch from the "qa" branch here the "qa" would be parent and "hotfix_3" the child. Usually at the root of the tree you will have the "master" (so it has no parent).

>Are both of them hosted on platform.sh? (If so, how do we know which is which?)
Yes. This is about two branches on Platform.sh both of which having an active environment.
>Or are they referring to a developer's local environment (e.g. running on a laptop) vs remote environments hosted on platform.sh?
No
> What happens if a static file is present on the child, but not present in the parent? Will it remain in place, or be removed from the child environment?
See answer above.a
